language: php
php:
  - nightly
  - 7.2
  - 7.1
matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer selfupdate
  - composer update --no-interaction --prefer-dist
  - composer require codeclimate/php-test-reporter:dev-master --dev

script:
  - ./vendor/phpunit/phpunit/phpunit -v --coverage-clover build/logs/clover.xml

after_script:
  - CODECLIMATE_REPO_TOKEN=8a8170916e1a278ded9904c1f0b8df5882dde058eef396adf9f206a053699758 ./vendor/bin/test-reporter